var express = require('express');
var router = express.Router();

const itemList = [
  { 'id': 1, 'Term': 'DevOps', 'Description': 'DevOps defines a development and operations, enabling automated development and continuous feature deliveries through collaboration, faster value delivery, and problem resolution. Tailored DevOps approaches can facilitate quick and reliable upgrades, even in constrained environments like safety-critical and embedded systems.', 'Refrences': 'Ebert, C., Gallardo, G., Hernantes, J. and Serrano, N., 2016. DevOps. Ieee Software, 33(3), pp.94-100.' },
  { 'id': 2, 'Term': 'Continuous Integration', 'Description': 'In DevOps, It defines a method where code updates are routinely merged into a main repository and tested automatically, promoting frequent collaboration and a consistent codebase.', 'Refrences': 'Ishan, G. (2023), What is Continuous Integration and Why it is Important?,Simplilearn, accessed 21 July 2023. https://www.simplilearn.com/tutorials/devops-tutorial/continuous-integration ' },
  { 'id': 3, 'Term': 'Continuous delivery', 'Description': 'Continuous Delivery extends Continuous Integration by automating code deployment to testing or production environments, allowing one-click application deployment at any preferred frequency. Early production deployment is essential to leverage its benefits, ensuring smaller releases for easier issue troubleshooting.', 'Refrences': 'Sten, P. (n.d.). Continuous integration vs. delivery vs. deployment, ATLASSIAN, accessed 21 July 2023 https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment' },
  { 'id': 4, 'Term': 'Continuous deployment', 'Description': 'Continuous Deployment defines an automated software development strategy where code changes are automatically released to production after passing predefined tests. It speeds up time-to-market by eliminating delays and the need for manual regression testing and approval meetings for most changes.', 'Refrences': 'IBM.(n.d.).What is continuous deployment?, IBM, accessed 21 July 2023.' },
  { 'id': 5, 'Term': 'NoOps', 'Description': 'NoOps is a concept where IT environments are highly automated, eliminating the need for dedicated teams to manage software. It leverages cloud solutions to provide resources on demand, enabling faster application deployment and a more business-oriented focus for developers.', 'Refrences': 'Rahul, Aeati. (2021). NoOps (no operations). TechTarget, accessed 21 July 2023. https://www.techtarget.com/searchitoperations/definition/NoOps' },
  { 'id': 6, 'Term': 'BDD & TDD', 'Description': 'It defines a testing methods. Test-Driven Development (TDD) is a testing methodology where a QA engineer writes test cases for each small functionality to validate code from a developers perspective. Behavioral-Driven Development (BDD) is derived from TDD and focuses on testing system behavior with different feature development approaches. BDD commonly uses the Given-When-Then approach for writing test cases.', 'Refrences': 'Jash, U. (2023).TDD vs BDD vs ATDD : Key Differences. BrowersStack, accessed 21 July 2023. https://www.browserstack.com/guide/tdd-vs-bdd-vs-atdd#:~:text=TDD%20is%20a%20development%20technique,more%20on%20capturing%20the%20requirements' },
  { 'id': 7, 'Term': 'Agile', 'Description': 'It is a software development approach that emphasises rapid delivery through enhanced collaboration between the client and development team.It can ensure that the developed software meets the business and functional requirements.', 'Refrences': 'Gursimran, S. (2023). Role of Agile in DevOps-why it Matters?. XENONSTACK, accessed 21 July 2023. https://www.xenonstack.com/insights/role-of-agile-in-devops/#:~:text=Introduction%20to%20Agile%20in%20DevOps,-Every%20IT%20company&text=It%20is%20a%20methodology%20used,client%20and%20the%20development%20team.' },
  { 'id': 8, 'Term': 'key performance indicators', 'Description': 'KPIs are measurable metrics used to track progress towards goals, guiding data-driven decisions for performance optimization. They help organizations identify strengths, weaknesses, and take actions to improve overall performance.', 'Refrences': 'Klipfolio. (n.d.). What is a Key Performance Indicator (KPI)?, Klipfolio,accessed 21 July 2023. https://www.klipfolio.com/resources/articles/what-is-a-key-performance-indicator' },
  { 'id': 9, 'Term': 'Service-Level Agreements', 'Description': 'It defines a contract that stipulates the expected standards of service from a provider. It outlines key metrics, expectations, and consequences for non-compliance.', 'Refrences': 'Andrey, p. (2017). What is an SLA? Best practices for service-level agreements.CIO, accessed 21 July 2023. https://www.cio.com/article/274740/outsourcing-sla-definitions-and-solutions.html ' },
  { 'id': 10, 'Term': 'Infrastructure as code', 'Description': 'Infrastructure as Code (IaC) manages infrastructure through code, enabling easy configuration editing and consistency, while promoting documentation and avoiding ad hoc changes. Examples include AWS CloudFormation, Ansible, Chef, Puppet, SaltStack, and Terraform.', 'Refrences': 'Morris, K., 2020. Infrastructure as code. OReilly Media.' },
  { 'id': 11, 'Term': 'The definition of done (DoD)', 'Description': 'DoD (Definition of Done) refers to the state when all conditions and acceptance criteria are met, and the product is ready to be accepted by users, customers, and the team.', 'Refrences': 'ProductPlan.(n.d.).The Definition of Done: What Product Managers Need to Know. prodctPlan, accessed 4 Aug 2023.https://www.productplan.com/learn/agile-definition-of-done/#:~:text=%E2%80%9CThe%20definition%20of%20done%20(DoD,of%20done%20to%20ensure%20quality.' },
  { 'id': 12, 'Term': 'root cause analysis (RCA)', 'Description': 'Root Cause Analysis (RCA) is the process of identifying the fundamental reasons for a problem to determine appropriate solutions.', 'Refrences': 'Tableau.(n.d.).Root Cause Analysis Explained: Definition, Examples, and Methods.Tebleau, accessed 4 Aug 2023.https://www.tableau.com/learn/articles/root-cause-analysis#definition ' },
  { 'id': 13, 'Term': 'IT Infrastructure Library (ITIL)', 'Description': 'ITIL is a comprehensive IT service management framework that guides businesses in delivering IT services effectively. It aids in risk management, improving customer relationships, and establishing a stable and efficient IT environment that facilitates growth and adaptability.', 'Refrences': 'White, S. K., & Greiner, L. (2022). What is ITIL? Your guide to the IT Infrastructure Library.CIO.accessed 4 Aug 2023.https://www.cio.com/article/272361/infrastructure-it-infrastructure-library-itil-definition-and-solutions.html' },
  { 'id': 14, 'Term': 'DevSecOps', 'Description': 'DevOps is a collaborative and automated approach between development and operations teams. DevSecOps extends this by integrating security practices into each stage of the software development lifecycle to ensure software security and compliance.', 'Refrences': 'jamasoftware.(n.d.).Follow a manual added link The Essential Guide to Requirements Management and Traceability.Jama software. accessed 4 Aug 2023.https://www.jamasoftware.com/requirements-management-guide' },
  { 'id': 15, 'Term': 'Definition of Ready (DoR)', 'Description': 'A Definition of Ready (DoR) outlines the necessary criteria for an item to be ready for implementation work. It specifies the requirements that must be met before work can begin on the item in the intake process.', 'Refrences': 'Nick, B.(2022). Definition of ready and definition of done: Whats the difference?.BOOST.accessed 4 Aug 2023.https://www.boost.co.nz/blog/2022/06/definition-ready-definition-done' },
  { 'id': 16, 'Term': 'User Experience (UX)', 'Description': 'User Experience (UX) is how individuals perceive and interact with a system, such as websites or applications. UX designers study usability, value perception, efficiency, and practicality to enhance the overall user experience.', 'Refrences': 'Jacob, G.(2010).What Is User Experience Design? Overview, Tools And Resources.accessed 4 Aug 2023. https://www.smashingmagazine.com/2010/10/what-is-user-experience-design-overview-tools-and-resources/' },
  { 'id': 17, 'Term': 'Configuration as Code (CaC)', 'Description': 'Config as Code (CaC) separates configuration from the application code, storing application settings in a separate repository and managing them independently. This allows for more flexibility and ease of configuration management.', 'Refrences': 'Adam, B. (2021).Config as Code: What is it and how is it beneficial?.Octopus Deploy.accessed 4 Aug 2023.https://octopus.com/blog/config-as-code-what-is-it-how-is-it-beneficial ' },
  { 'id': 18, 'Term': 'Desired State Configuration (DSC)', 'Description': 'DSC (Desired State Configuration) is a command-line tool that empowers administrators to utilize a PowerShell-based scripting language for configuring Windows and/or Linux systems. It automates the configuration of multiple computers, ensuring uniform settings across them.', 'Refrences': 'Brien, P.(n.d.).Microsoft Windows PowerShell DSC (Desired State Configuration).TechTarget,accessed 4 Aug 2023.https://www.techtarget.com/searchwindowsserver/definition/Microsoft-Windows-PowerShell-DSC-Desired-State-Configuration#:~:text=DSC%20can%20be%20used%20to,referred%20to%20as%20push%20mode. ' },
  { 'id': 19, 'Term': 'Site Reliability Engineering (SRE)', 'Description': 'Site Reliability Engineering (SRE) is an IT operations approach that relies on software engineering principles, using automation and software tools to manage production systems and resolve issues. It replaces manual tasks typically performed by operations teams with automated solutions.', 'Refrences': 'RedHat.(2020).What is SRE (site reliability engineering)?.RedHat.accessed 4 Aug 2023.https://www.redhat.com/en/topics/devops/what-is-sre' },
  { 'id': 20, 'Term': 'Architecture Development Method (ADM)', 'Description': 'The Architecture Development Method (ADM) is the central process within TOGAF that enables the development of enterprise architecture to address the business and IT needs of an organization. It offers a structured approach for managing the enterprise architecture lifecycle, allowing for customization based on organizational requirements and facilitating architecture planning activities.', 'Refrences': 'Cybermedian,(2020).Introduction to TOGAF Architecture Development Method (ADM).Cybermedian,accessed 4 Aug 2023.https://www.cybermedian.com/introduction-to-togaf-architecture-development-method-adm/' },
];




/* GET home page. */
router.get('/', function (req, res, next) {
  res.render('index', {
    title: 'SIT722 DevOps Glossary', subheading: 'my website showing a collection of DevOps terms and their brief descriptions',
    items: itemList
  });
});

module.exports = router;
